name: Deploy npd-dev Infrastructure
run-name: ${{ github.workflow }} triggered by ${{ github.actor }}

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  Create-Changeset:
    runs-on: default
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Assume CICD Role
        uses: CBA-General/rrcs-common-actions/cs-aws-assume-deploy-role@main
        with:
          workload-account-id: ${{ vars.AWS_ACCOUNT_ID_NPD_DEV }}
          workload-deploy-role: ${{ vars.AWS_DEPLOY_ROLE_COMMON }}
          github-trust-role: ${{ vars.AWS_TRUST_ROLE_COMMON }}
          aws-region: ${{ vars.AWS_REGION_COMMON  }}
      - name: whoami
        run: aws sts get-caller-identity
      - name: Create Changeset
        run: |
          chmod +x scripts/create-changeset.sh
          scripts/create-changeset.sh --environment-name npd-dev --debug true
     

  Deploy:
    needs: Create-Changeset
    runs-on: default
    environment: Manual-Approval
    steps:
      - name: Changeset Approval 
        run: echo "The Changeset has been approved, proceeding to Deploy-Changeset."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Assume CICD Role
        uses: CBA-General/rrcs-common-actions/cs-aws-assume-deploy-role@main
        with:
          workload-account-id: ${{ vars.AWS_ACCOUNT_ID_NPD_DEV }}
          workload-deploy-role: ${{ vars.AWS_DEPLOY_ROLE_COMMON }}
          github-trust-role: ${{ vars.AWS_TRUST_ROLE_COMMON }}
          aws-region: ${{ vars.AWS_REGION_COMMON  }}
      - name: whoami
        run: aws sts get-caller-identity
      - name: Deploy Infra
        run: |
          chmod +x scripts/deploy.sh
          echo "Deploying the changeset"
          scripts/deploy.sh --environment-name npd-dev --debug true

      
