AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 Bucket

Parameters:
  BucketName:
    Type: String
    Description: The base name of the S3 bucket
  Environment:
    Type: String
    Description: The environment name (e.g., npd-dev, nft-internal)

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${BucketName}-${Environment}'
