AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Sydney S3 bucket

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket
  VersioningConfigurationStatus:
    Type: String
    AllowedValues:
      - Enabled
      - Suspended
    Description: The versioning status of the S3 bucket
  Environment:
    Type: String
    Description: The environment tag for the S3 bucket

Resources:
  SydneyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !Ref VersioningConfigurationStatus
      Tags:
        - Key: Environment
          Value: !Ref Environment
