name: Deploy S3 Bucket

on:
  push:
    branches:
      - develop
      # - nft-internal
      # - nft-customer
      # - prd-internal
      # - prd-customer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        if: github.ref == 'refs/heads/develop'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "ASIAWYPC577XI6AEQ6JZ"
          aws-secret-access-key: "cFzIRXt5nvtXgHwugZEHkba0J1kAXIUwtkABRTe5"
          aws-session-token: |
            IQoJb3JpZ2luX2VjENn//////////wEaCXVzLWVhc3QtMSJHMEUCIGmEg6egBh+z8Z7SCx4PuV5unIrDiDCAKvyISAPky3sYAiEA7Lkcu300xoPevzDB8PzRsAtVsFruVy3/c73blW5BEhYqwQIIIhACGgw0NjQ4NjkyNjEyOTQiDN4MTg01pQIRsujjJSqeAk0qUic5zey+M27mqszyKQGkiF6TB75mRPeWk6VHJdeFhxeDTpX4OJofuz2kqaY8pUQYEsaJ3OV5FkTlkAkZD/j2t+rSYUg8Og+lHNKq9BYW5GXmq+cGKxbtlDkMghfUwCAKXDULYtDMZrUM+8ZxHCFIfpJbrL07ZwZhdY4oWjl6qzboyIsuOr+xh7iZD2wEmu5qsPNGM43VEmAM1P5AtXVNrVUJmdygDClLCfJ3NRunaiRCUHSDTJ5tc6mpU7FZ5h13DyS8gYNX19lGDjy1p+x7/rAhHSp57Ot8Ai/XjDzRV8VUgkvXb1M4lOMHr7GrlcN3kONQcFTrX9OdDozI186q/80GTdmoBACBv8s+gi9Pt67HDppmY2wvQgBt5How3vzXtwY63QEVkcE7UmlTT7gW7MzVyLBjVI0NCqt+Ws3bXXTRepSe8+gkDfyLyraD8W7I318T1nAdGDMdm1H7ZVDkW/vFkkMcxkXZUmQw9VVfSMl5Hyg707ll55JhCcmdXcthO2dsjPojnQXtK7TEjnBWjV7hW/GN+wIsngSO5af4FDothkfV6005GZptnkjBXWhsDdbZZP/CHWB0+t5X5CvJwX1ieaBCqy1CXLzl+jcgt+9gwa7ccId912sAiuXJg/WesHkd+IJvenE6TB8C9vsP6TwENs0yJed3boi2zFjApPrIVA==
          aws-region: "ap-southeast-2"

      # - name: Set up AWS CLI (nft-internal)
      #   if: github.ref == 'refs/heads/nft-internal'
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.NFT_INTERNAL_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.NFT_INTERNAL_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.NFT_INTERNAL_AWS_REGION }}

      # - name: Set up AWS CLI (nft-customer)
      #   if: github.ref == 'refs/heads/nft-customer'
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.NFT_CUSTOMER_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.NFT_CUSTOMER_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.NFT_CUSTOMER_AWS_REGION }}

      # - name: Set up AWS CLI (prd-internal)
      #   if: github.ref == 'refs/heads/prd-internal'
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.PRD_INTERNAL_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.PRD_INTERNAL_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.PRD_INTERNAL_AWS_REGION }}

      # - name: Set up AWS CLI (prd-customer)
      #   if: github.ref == 'refs/heads/prd-customer'
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.PRD_CUSTOMER_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.PRD_CUSTOMER_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.PRD_CUSTOMER_AWS_REGION }}

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file Infrastructure/Templates/S3/s3.yml \
            --stack-name my-s3-bucket-stack-${{ github.ref_name }} \
            --parameter-overrides BucketName=my-s3-bucket-${{ github.run_id }} \
            --capabilities CAPABILITY_IAM

