name: Deploy npd-dev

on:
  push:
    branches:
      - develop

jobs:
  Create-Changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI for develop
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-2"

      - name: whoami
        run: aws sts get-caller-identity

      - name: Create Changeset
        run: |
          chmod +x Scripts/manage-infrastructure.sh
          echo "Creation of changeset"
          Scripts/manage-infrastructure.sh --environment-name "npd-dev" --action "create-changeset" --debug true
  
  Deploy-Changeset:
    needs: Create-Changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI for develop
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-2"

      - name: whoami
        run: aws sts get-caller-identity

      - name: Deploy Changeset
        run: |
          chmod +x Scripts/manage-infrastructure.sh
          echo "Deploying the changeset"
          Scripts/manage-infrastructure.sh --environment-name "npd-dev" --action "deploy" --debug true
