name: Deploy npd-dev

on:
  push:
    branches:
        - develop
      # - nft-internal
      # - nft-customer
      # - prd-internal
      # - prd-customer

jobs:
  Create-Changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up AWS CLI for develop
        if: github.ref == 'refs/heads/develop'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-2"
      - name: whoami
        run: aws sts get-caller-identity
      - name: Create Changeset
        run: |
          chmod +x Scripts/create-changeset.sh
          echo "Creation of changeset"
          Scripts/create-changeset.sh --environment-name npd-dev --debug true
      
      - name: Execute Changeset
        run: |
          chmod +x Scripts/deploy.sh
          echo "Deploying the changeset"
          Scripts/deploy.sh --environment-name npd-dev --debug true
