name: Deploy S3 Bucket

on:
  push:
    branches:
      - develop
      # - nft-internal
      # - nft-customer
      # - prd-internal
      # - prd-customer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        if: github.ref == 'refs/heads/develop'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "ASIAWYPC577XGFYCRTXP"
          aws-secret-access-key: "rAEenZJ8uMr8LhOdyH2mRwouRtwj8MukEL1N36FF"
          aws-session-token: |
            IQoJb3JpZ2luX2VjEB8aCXVzLWVhc3QtMSJGMEQCIFGZZbTMxYfSPGx3n2PaDr+mK9b7l37VsS5a7nYmuXvuAiAhZuGJgHQ7fu29UoWaG9ya4ZixFiFvLPLYZHobu5CEDCrBAghoEAIaDDQ2NDg2OTI2MTI5NCIMRVaDKvXz87oTd/QYKp4CXxIcYJhB33uo0oULFIJ759trumrBrSv2YI5/KfGfx6E0/RK8F35qMCWmfxtGUjXd5EYo7HssG81NKmTiTADsaVyyVJM7/xzS8U0dwhhOXdneT5bmHjHvkrCxwYzIQoRMtUEmxM1JxlNwGwMiltlQGP6Q+pkrhGGahu0RYOxe29DwEfjBQvUsFwZEpQ/81jV5RHd9EbtDTWDWJa1ht46LMbsPDvha/Bw7oAM7TVAZyOqGuYExs9BBDYRXvk87ZeibKNjvd5QAOCjrWgBxn3kn4v9vUZWaPsqgBCA7gcrUiA0qwSbA9z+HBrE2AA0pPqPR9605rtBP57sj0Y5NAIrkv4t1cGd0+OCT0KcqsBiRHfYthYHh1UlWjDC9aynj+zCMqee3BjreAXE9ZMYwLMe1l0ZCmtFP45Zc8vUGxw/rI20X/+vR9dWv0lWQEBRXC9IUtNtWvAXhoFCq0PSoxzBzgteOYSywouJ3nvJM6FMhgmSmdEk8i4eujEry8YViJEuBBqfCV9QF+utJrhi4BKdM+V8H4pjXkGwE0e4UL9eBmIpZ010DY11knScqc/B5zMUtAOcDCPEyhTPZMkQscIK4R3aCJYxFHZKOs1K9zigCYZwDVrJwsVUqT/67HI3HiTrqYkJStq+LsXjqrU8iMqkTBI7CaZTTpYiKpQEbpCGgoUwYflzF/g==
          aws-region: "ap-southeast-2"

      # - name: Set up AWS CLI (nft-internal)
      #   if: github.ref == 'refs/heads/nft-internal'
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.NFT_INTERNAL_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.NFT_INTERNAL_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.NFT_INTERNAL_AWS_REGION }}

      # - name: Set up AWS CLI (nft-customer)
      #   if: github.ref == 'refs/heads/nft-customer'
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.NFT_CUSTOMER_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.NFT_CUSTOMER_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.NFT_CUSTOMER_AWS_REGION }}

      # - name: Set up AWS CLI (prd-internal)
      #   if: github.ref == 'refs/heads/prd-internal'
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.PRD_INTERNAL_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.PRD_INTERNAL_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.PRD_INTERNAL_AWS_REGION }}

      # - name: Set up AWS CLI (prd-customer)
      #   if: github.ref == 'refs/heads/prd-customer'
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.PRD_CUSTOMER_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.PRD_CUSTOMER_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.PRD_CUSTOMER_AWS_REGION }}

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file Infrastructure/Templates/S3/s3.yml \
            --stack-name my-s3-bucket-stack \
            --parameter-overrides BucketName=my-s3-bucket-iftekh-ee-elas \
            --capabilities CAPABILITY_IAM

