name: Deploy npd-dev

on:
  push:
    branches:
      - develop

jobs:
  Create-Changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up AWS CLI for develop
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-2"
      
      - name: whoami
        run: aws sts get-caller-identity
      
      - name: Install dependencies
        run: |
          for package in boto3 botocore argparse; do
            if ! python -c "import $package" &> /dev/null; then
              echo "Installing $package..."
              pip install $package
            else
              echo "$package is already installed."
            fi
          done

      - name: Create Changeset
        run: |
          echo "Creation of changeset"
          python Scripts/manage-infrastructure.py --environment-name "npd-dev" --action "create-changeset" --debug true
  
  Deploy-Changeset:
    needs: Create-Changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up AWS CLI for develop
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-2"
      
      - name: whoami
        run: aws sts get-caller-identity
      
      - name: Install dependencies
        run: |
          for package in boto3 botocore argparse; do
            if ! python -c "import $package" &> /dev/null; then
              echo "Installing $package..."
              pip install $package
            else
              echo "$package is already installed."
            fi
          done

      - name: Deploy Changeset
        run: |
          echo "Deploying the changeset"
          python Scripts/manage-infrastructure.py --environment-name "npd-dev" --action "deploy" --debug true
