name: Deploy Nonprod Environments

on:
  push:
    branches:
      - nonprod
    paths:
      - 'infrastructure/parameters/nonprod/develop/**'
      - 'infrastructure/parameters/nonprod/st/**'
      - 'infrastructure/parameters/nonprod/sit/**'

permissions:
  id-token: write
  contents: read

jobs:
  Create-Changeset:
    runs-on: default
    environment: test-otds-nonprod
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Assume CICD Role
        uses: CBA-General/rrcs-common-actions/cs-aws-assume-deploy-role@main
        with:
          workload-account-id: ${{ vars.AWS_ACCOUNT_ID }}
          workload-deploy-role: ${{ vars.AWS_DEPLOY_ROLE }}
          github-trust-role: ${{ vars.AWS_TRUST_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: whoami
        run: aws sts get-caller-identity

      - name: Create Changeset - Develop
        if: "github.event.head_commit.modified && github.event_name == 'push' && github.event.ref == 'refs/heads/nonprod'"
        run: echo "Creating changeset for Develop environment..."

      - name: Create Changeset - St
        if: "github.event.head_commit.modified && github.event_name == 'push' && github.event.ref == 'refs/heads/nonprod'"
        run: echo "Creating changeset for St environment..."

      - name: Create Changeset - Sit
        if: "github.event.head_commit.modified && github.event_name == 'push' && github.event.ref == 'refs/heads/nonprod'"
        run: echo "Creating changeset for Sit environment..."

  Manual_approval:
    needs: Create-Changeset
    runs-on: default
    environment: Manual-Approval
    steps:
      - name: Awaiting Manual Review
        run: echo "The Changeset has been approved, proceeding to Deploy-Changeset."

  Deploy-Changeset:
    needs: Manual_approval
    runs-on: default
    environment: test-otds-nonprod
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Assume CICD Role
        uses: CBA-General/rrcs-common-actions/cs-aws-assume-deploy-role@main
        with:
          workload-account-id: ${{ vars.AWS_ACCOUNT_ID }}
          workload-deploy-role: ${{ vars.AWS_DEPLOY_ROLE }}
          github-trust-role: ${{ vars.AWS_TRUST_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: whoami
        run: aws sts get-caller-identity

      - name: Deploy Changeset - Develop
        if: "contains(github.event.head_commit.message, 'develop')"
        run: echo "Deploying the changeset for Develop environment..."

      - name: Deploy Changeset - St
        if: "contains(github.event.head_commit.message, 'st')"
        run: echo "Deploying the changeset for St environment..."

      - name: Deploy Changeset - Sit
        if: "contains(github.event.head_commit.message, 'sit')"
        run: echo "Deploying the changeset for Sit environment..."
